# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ansalemo-devops-wafc-sp'
  imageRepository: 'wafcdevops'
  containerRegistry: 'ansalemocontainerregistry.azurecr.io'
  dockerfilePath: './azure-devops/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ansalemo-devops-wafc-sp'
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: './azure-devops/Dockerfile'

- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Ansalemo(4388fa06-bf66-4497-82c2-991ba75ecb97)'
        appType: 'webAppContainer'
        WebAppName: 'ansalemo-devops-image'
        DockerNamespace: 'ansalemocontainerregistry.azurecr.io'
        DockerRepository: '$(imageRepository)'
        DockerImageTag: '$(tag)'
        AppSettings: '-WEBSITES_PORT 3000'
