# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - yoursite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      run: docker login youracr.azurecr.io --username ${{ secrets.SP_APP_ID }} --password ${{ secrets.SP_PASSWD }}
      

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: youracr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0000000000000000000000000 }}/wafc-githubactions:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    # You can use this to set App Settings - see here on setting this up - https://github.com/marketplace/actions/azure-app-service-settings
    # - uses: azure/login@v1
    #   with:
    #     creds: '${{ secrets.AZURE_CREDENTIALS }}'

    # - uses: azure/appservice-settings@v1
    #   with:
    #     app-name: 'yoursite'
    #     app-settings-json: '[{ "WEBSITES_PORT": "3000" }]'

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'yoursite'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0000000000000000000000000 }}
        images: 'youracr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0000000000000000000000000 }}/wafc-githubactions:${{ github.sha }}'